/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_lastSelCharacter = new Property();
			pAccount_lastSelCharacter.name = "lastSelCharacter";
			pAccount_lastSelCharacter.properUtype = 2;
			pAccount_lastSelCharacter.properFlags = 32;
			pAccount_lastSelCharacter.aliasID = 4;
			UInt64 Account_lastSelCharacter_defval;
			UInt64.TryParse("0", out Account_lastSelCharacter_defval);
			pAccount_lastSelCharacter.defaultVal = Account_lastSelCharacter_defval;
			pAccountModule.propertys["lastSelCharacter"] = pAccount_lastSelCharacter; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_lastSelCharacter.aliasID] = pAccount_lastSelCharacter;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(lastSelCharacter / 2).");

			pAccountModule.useMethodDescrAlias = true;
			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[2] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_component1 = new Property();
			pAvatar_component1.name = "component1";
			pAvatar_component1.properUtype = 6;
			pAvatar_component1.properFlags = 253;
			pAvatar_component1.aliasID = 4;
			pAvatarModule.propertys["component1"] = pAvatar_component1; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component1.aliasID] = pAvatar_component1;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component1 / 6).");

			Property pAvatar_level = new Property();
			pAvatar_level.name = "level";
			pAvatar_level.properUtype = 41002;
			pAvatar_level.properFlags = 8;
			pAvatar_level.aliasID = 5;
			UInt16 Avatar_level_defval;
			UInt16.TryParse("", out Avatar_level_defval);
			pAvatar_level.defaultVal = Avatar_level_defval;
			pAvatarModule.propertys["level"] = pAvatar_level; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_level.aliasID] = pAvatar_level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(level / 41002).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 41003;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 6;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 41003).");

			List<DATATYPE_BASE> pAvatar_onGameBegine_args = new List<DATATYPE_BASE>();
			pAvatar_onGameBegine_args.Add(EntityDef.id2datatypes[5]);

			Method pAvatar_onGameBegine = new Method();
			pAvatar_onGameBegine.name = "onGameBegine";
			pAvatar_onGameBegine.methodUtype = 5;
			pAvatar_onGameBegine.aliasID = 1;
			pAvatar_onGameBegine.args = pAvatar_onGameBegine_args;

			pAvatarModule.methods["onGameBegine"] = pAvatar_onGameBegine; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onGameBegine.aliasID] = pAvatar_onGameBegine;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onGameBegine / 5).");

			List<DATATYPE_BASE> pAvatar_onRspFrameMessage_args = new List<DATATYPE_BASE>();
			pAvatar_onRspFrameMessage_args.Add(EntityDef.id2datatypes[32]);

			Method pAvatar_onRspFrameMessage = new Method();
			pAvatar_onRspFrameMessage.name = "onRspFrameMessage";
			pAvatar_onRspFrameMessage.methodUtype = 4;
			pAvatar_onRspFrameMessage.aliasID = 2;
			pAvatar_onRspFrameMessage.args = pAvatar_onRspFrameMessage_args;

			pAvatarModule.methods["onRspFrameMessage"] = pAvatar_onRspFrameMessage; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onRspFrameMessage.aliasID] = pAvatar_onRspFrameMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onRspFrameMessage / 4).");

			List<DATATYPE_BASE> pAvatar_reqFrameChange_args = new List<DATATYPE_BASE>();
			pAvatar_reqFrameChange_args.Add(EntityDef.id2datatypes[31]);

			Method pAvatar_reqFrameChange = new Method();
			pAvatar_reqFrameChange.name = "reqFrameChange";
			pAvatar_reqFrameChange.methodUtype = 1;
			pAvatar_reqFrameChange.aliasID = -1;
			pAvatar_reqFrameChange.args = pAvatar_reqFrameChange_args;

			pAvatarModule.methods["reqFrameChange"] = pAvatar_reqFrameChange; 
			pAvatarModule.cell_methods["reqFrameChange"] = pAvatar_reqFrameChange;

			pAvatarModule.idcell_methods[pAvatar_reqFrameChange.methodUtype] = pAvatar_reqFrameChange;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqFrameChange / 1).");

			ScriptModule pOperationModule = new ScriptModule("Operation");
			EntityDef.moduledefs["Operation"] = pOperationModule;
			EntityDef.idmoduledefs[3] = pOperationModule;

			Property pOperation_position = new Property();
			pOperation_position.name = "position";
			pOperation_position.properUtype = 40000;
			pOperation_position.properFlags = 4;
			pOperation_position.aliasID = 1;
			Vector3 Operation_position_defval = new Vector3();
			pOperation_position.defaultVal = Operation_position_defval;
			pOperationModule.propertys["position"] = pOperation_position; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_position.aliasID] = pOperation_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(position / 40000).");

			Property pOperation_direction = new Property();
			pOperation_direction.name = "direction";
			pOperation_direction.properUtype = 40001;
			pOperation_direction.properFlags = 4;
			pOperation_direction.aliasID = 2;
			Vector3 Operation_direction_defval = new Vector3();
			pOperation_direction.defaultVal = Operation_direction_defval;
			pOperationModule.propertys["direction"] = pOperation_direction; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_direction.aliasID] = pOperation_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(direction / 40001).");

			Property pOperation_spaceID = new Property();
			pOperation_spaceID.name = "spaceID";
			pOperation_spaceID.properUtype = 40002;
			pOperation_spaceID.properFlags = 16;
			pOperation_spaceID.aliasID = 3;
			UInt32 Operation_spaceID_defval;
			UInt32.TryParse("", out Operation_spaceID_defval);
			pOperation_spaceID.defaultVal = Operation_spaceID_defval;
			pOperationModule.propertys["spaceID"] = pOperation_spaceID; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_spaceID.aliasID] = pOperation_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(spaceID / 40002).");

			Property pOperation_isWathcher = new Property();
			pOperation_isWathcher.name = "isWathcher";
			pOperation_isWathcher.properUtype = 10;
			pOperation_isWathcher.properFlags = 16;
			pOperation_isWathcher.aliasID = 4;
			SByte Operation_isWathcher_defval;
			SByte.TryParse("0", out Operation_isWathcher_defval);
			pOperation_isWathcher.defaultVal = Operation_isWathcher_defval;
			pOperationModule.propertys["isWathcher"] = pOperation_isWathcher; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_isWathcher.aliasID] = pOperation_isWathcher;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(isWathcher / 10).");

			Property pOperation_lossScore = new Property();
			pOperation_lossScore.name = "lossScore";
			pOperation_lossScore.properUtype = 9;
			pOperation_lossScore.properFlags = 16;
			pOperation_lossScore.aliasID = 5;
			Int32 Operation_lossScore_defval;
			Int32.TryParse("0", out Operation_lossScore_defval);
			pOperation_lossScore.defaultVal = Operation_lossScore_defval;
			pOperationModule.propertys["lossScore"] = pOperation_lossScore; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_lossScore.aliasID] = pOperation_lossScore;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(lossScore / 9).");

			Property pOperation_state = new Property();
			pOperation_state.name = "state";
			pOperation_state.properUtype = 7;
			pOperation_state.properFlags = 16;
			pOperation_state.aliasID = 6;
			SByte Operation_state_defval;
			SByte.TryParse("", out Operation_state_defval);
			pOperation_state.defaultVal = Operation_state_defval;
			pOperationModule.propertys["state"] = pOperation_state; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_state.aliasID] = pOperation_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(state / 7).");

			Property pOperation_winScore = new Property();
			pOperation_winScore.name = "winScore";
			pOperation_winScore.properUtype = 8;
			pOperation_winScore.properFlags = 16;
			pOperation_winScore.aliasID = 7;
			Int32 Operation_winScore_defval;
			Int32.TryParse("0", out Operation_winScore_defval);
			pOperation_winScore.defaultVal = Operation_winScore_defval;
			pOperationModule.propertys["winScore"] = pOperation_winScore; 

			pOperationModule.usePropertyDescrAlias = true;
			pOperationModule.idpropertys[(UInt16)pOperation_winScore.aliasID] = pOperation_winScore;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), property(winScore / 8).");

			List<DATATYPE_BASE> pOperation_onCreateSpaceResult_args = new List<DATATYPE_BASE>();
			pOperation_onCreateSpaceResult_args.Add(EntityDef.id2datatypes[5]);

			Method pOperation_onCreateSpaceResult = new Method();
			pOperation_onCreateSpaceResult.name = "onCreateSpaceResult";
			pOperation_onCreateSpaceResult.methodUtype = 16;
			pOperation_onCreateSpaceResult.aliasID = 1;
			pOperation_onCreateSpaceResult.args = pOperation_onCreateSpaceResult_args;

			pOperationModule.methods["onCreateSpaceResult"] = pOperation_onCreateSpaceResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onCreateSpaceResult.aliasID] = pOperation_onCreateSpaceResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onCreateSpaceResult / 16).");

			List<DATATYPE_BASE> pOperation_onLoginOutSpaceResult_args = new List<DATATYPE_BASE>();
			pOperation_onLoginOutSpaceResult_args.Add(EntityDef.id2datatypes[8]);
			pOperation_onLoginOutSpaceResult_args.Add(EntityDef.id2datatypes[5]);

			Method pOperation_onLoginOutSpaceResult = new Method();
			pOperation_onLoginOutSpaceResult.name = "onLoginOutSpaceResult";
			pOperation_onLoginOutSpaceResult.methodUtype = 18;
			pOperation_onLoginOutSpaceResult.aliasID = 2;
			pOperation_onLoginOutSpaceResult.args = pOperation_onLoginOutSpaceResult_args;

			pOperationModule.methods["onLoginOutSpaceResult"] = pOperation_onLoginOutSpaceResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onLoginOutSpaceResult.aliasID] = pOperation_onLoginOutSpaceResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onLoginOutSpaceResult / 18).");

			List<DATATYPE_BASE> pOperation_onLoginSpaceResult_args = new List<DATATYPE_BASE>();
			pOperation_onLoginSpaceResult_args.Add(EntityDef.id2datatypes[5]);

			Method pOperation_onLoginSpaceResult = new Method();
			pOperation_onLoginSpaceResult.name = "onLoginSpaceResult";
			pOperation_onLoginSpaceResult.methodUtype = 17;
			pOperation_onLoginSpaceResult.aliasID = 3;
			pOperation_onLoginSpaceResult.args = pOperation_onLoginSpaceResult_args;

			pOperationModule.methods["onLoginSpaceResult"] = pOperation_onLoginSpaceResult; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onLoginSpaceResult.aliasID] = pOperation_onLoginSpaceResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onLoginSpaceResult / 17).");

			List<DATATYPE_BASE> pOperation_onReqSpaceList_args = new List<DATATYPE_BASE>();
			pOperation_onReqSpaceList_args.Add(EntityDef.id2datatypes[29]);

			Method pOperation_onReqSpaceList = new Method();
			pOperation_onReqSpaceList.name = "onReqSpaceList";
			pOperation_onReqSpaceList.methodUtype = 15;
			pOperation_onReqSpaceList.aliasID = 4;
			pOperation_onReqSpaceList.args = pOperation_onReqSpaceList_args;

			pOperationModule.methods["onReqSpaceList"] = pOperation_onReqSpaceList; 
			pOperationModule.useMethodDescrAlias = true;
			pOperationModule.idmethods[(UInt16)pOperation_onReqSpaceList.aliasID] = pOperation_onReqSpaceList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(onReqSpaceList / 15).");

			List<DATATYPE_BASE> pOperation_reqCreateSpace_args = new List<DATATYPE_BASE>();

			Method pOperation_reqCreateSpace = new Method();
			pOperation_reqCreateSpace.name = "reqCreateSpace";
			pOperation_reqCreateSpace.methodUtype = 11;
			pOperation_reqCreateSpace.aliasID = -1;
			pOperation_reqCreateSpace.args = pOperation_reqCreateSpace_args;

			pOperationModule.methods["reqCreateSpace"] = pOperation_reqCreateSpace; 
			pOperationModule.base_methods["reqCreateSpace"] = pOperation_reqCreateSpace;

			pOperationModule.idbase_methods[pOperation_reqCreateSpace.methodUtype] = pOperation_reqCreateSpace;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqCreateSpace / 11).");

			List<DATATYPE_BASE> pOperation_reqLoginSpace_args = new List<DATATYPE_BASE>();
			pOperation_reqLoginSpace_args.Add(EntityDef.id2datatypes[5]);

			Method pOperation_reqLoginSpace = new Method();
			pOperation_reqLoginSpace.name = "reqLoginSpace";
			pOperation_reqLoginSpace.methodUtype = 13;
			pOperation_reqLoginSpace.aliasID = -1;
			pOperation_reqLoginSpace.args = pOperation_reqLoginSpace_args;

			pOperationModule.methods["reqLoginSpace"] = pOperation_reqLoginSpace; 
			pOperationModule.base_methods["reqLoginSpace"] = pOperation_reqLoginSpace;

			pOperationModule.idbase_methods[pOperation_reqLoginSpace.methodUtype] = pOperation_reqLoginSpace;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqLoginSpace / 13).");

			List<DATATYPE_BASE> pOperation_reqRemoveSpace_args = new List<DATATYPE_BASE>();
			pOperation_reqRemoveSpace_args.Add(EntityDef.id2datatypes[5]);

			Method pOperation_reqRemoveSpace = new Method();
			pOperation_reqRemoveSpace.name = "reqRemoveSpace";
			pOperation_reqRemoveSpace.methodUtype = 12;
			pOperation_reqRemoveSpace.aliasID = -1;
			pOperation_reqRemoveSpace.args = pOperation_reqRemoveSpace_args;

			pOperationModule.methods["reqRemoveSpace"] = pOperation_reqRemoveSpace; 
			pOperationModule.base_methods["reqRemoveSpace"] = pOperation_reqRemoveSpace;

			pOperationModule.idbase_methods[pOperation_reqRemoveSpace.methodUtype] = pOperation_reqRemoveSpace;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqRemoveSpace / 12).");

			List<DATATYPE_BASE> pOperation_reqSpaceList_args = new List<DATATYPE_BASE>();

			Method pOperation_reqSpaceList = new Method();
			pOperation_reqSpaceList.name = "reqSpaceList";
			pOperation_reqSpaceList.methodUtype = 10;
			pOperation_reqSpaceList.aliasID = -1;
			pOperation_reqSpaceList.args = pOperation_reqSpaceList_args;

			pOperationModule.methods["reqSpaceList"] = pOperation_reqSpaceList; 
			pOperationModule.base_methods["reqSpaceList"] = pOperation_reqSpaceList;

			pOperationModule.idbase_methods[pOperation_reqSpaceList.methodUtype] = pOperation_reqSpaceList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqSpaceList / 10).");

			List<DATATYPE_BASE> pOperation_reqGamePause_args = new List<DATATYPE_BASE>();

			Method pOperation_reqGamePause = new Method();
			pOperation_reqGamePause.name = "reqGamePause";
			pOperation_reqGamePause.methodUtype = 8;
			pOperation_reqGamePause.aliasID = -1;
			pOperation_reqGamePause.args = pOperation_reqGamePause_args;

			pOperationModule.methods["reqGamePause"] = pOperation_reqGamePause; 
			pOperationModule.cell_methods["reqGamePause"] = pOperation_reqGamePause;

			pOperationModule.idcell_methods[pOperation_reqGamePause.methodUtype] = pOperation_reqGamePause;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqGamePause / 8).");

			List<DATATYPE_BASE> pOperation_reqGameRunning_args = new List<DATATYPE_BASE>();

			Method pOperation_reqGameRunning = new Method();
			pOperation_reqGameRunning.name = "reqGameRunning";
			pOperation_reqGameRunning.methodUtype = 9;
			pOperation_reqGameRunning.aliasID = -1;
			pOperation_reqGameRunning.args = pOperation_reqGameRunning_args;

			pOperationModule.methods["reqGameRunning"] = pOperation_reqGameRunning; 
			pOperationModule.cell_methods["reqGameRunning"] = pOperation_reqGameRunning;

			pOperationModule.idcell_methods[pOperation_reqGameRunning.methodUtype] = pOperation_reqGameRunning;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqGameRunning / 9).");

			List<DATATYPE_BASE> pOperation_reqLoginOutSpace_args = new List<DATATYPE_BASE>();

			Method pOperation_reqLoginOutSpace = new Method();
			pOperation_reqLoginOutSpace.name = "reqLoginOutSpace";
			pOperation_reqLoginOutSpace.methodUtype = 7;
			pOperation_reqLoginOutSpace.aliasID = -1;
			pOperation_reqLoginOutSpace.args = pOperation_reqLoginOutSpace_args;

			pOperationModule.methods["reqLoginOutSpace"] = pOperation_reqLoginOutSpace; 
			pOperationModule.cell_methods["reqLoginOutSpace"] = pOperation_reqLoginOutSpace;

			pOperationModule.idcell_methods[pOperation_reqLoginOutSpace.methodUtype] = pOperation_reqLoginOutSpace;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqLoginOutSpace / 7).");

			List<DATATYPE_BASE> pOperation_reqReady_args = new List<DATATYPE_BASE>();
			pOperation_reqReady_args.Add(EntityDef.id2datatypes[6]);

			Method pOperation_reqReady = new Method();
			pOperation_reqReady.name = "reqReady";
			pOperation_reqReady.methodUtype = 6;
			pOperation_reqReady.aliasID = -1;
			pOperation_reqReady.args = pOperation_reqReady_args;

			pOperationModule.methods["reqReady"] = pOperation_reqReady; 
			pOperationModule.cell_methods["reqReady"] = pOperation_reqReady;

			pOperationModule.idcell_methods[pOperation_reqReady.methodUtype] = pOperation_reqReady;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Operation), method(reqReady / 6).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "ENTITY_SUBSTATE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "FRAMEID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "ENTITY_STATE";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_FORBIDS";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_FORBID_COUNTER";
				DATATYPE_ENTITY_FORBID_COUNTER datatype = new DATATYPE_ENTITY_FORBID_COUNTER();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITYID_LIST";
				DATATYPE_ENTITYID_LIST datatype = new DATATYPE_ENTITYID_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "AVATAR_DATA";
				DATATYPE_AVATAR_DATA datatype = new DATATYPE_AVATAR_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "AVATAR_INFOS";
				DATATYPE_AVATAR_INFOS datatype = new DATATYPE_AVATAR_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "AVATAR_INFOS_LIST";
				DATATYPE_AVATAR_INFOS_LIST datatype = new DATATYPE_AVATAR_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "SPACE_INFO";
				DATATYPE_SPACE_INFO datatype = new DATATYPE_SPACE_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "SPACE_LIST";
				DATATYPE_SPACE_LIST datatype = new DATATYPE_SPACE_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "ENTITY_DATA";
				DATATYPE_ENTITY_DATA datatype = new DATATYPE_ENTITY_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 32;
				string typeName = "FRAME_DATA";
				DATATYPE_FRAME_DATA datatype = new DATATYPE_FRAME_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 34;
				string typeName = "FRAME_LIST";
				DATATYPE_FRAME_LIST datatype = new DATATYPE_FRAME_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 36;
				string typeName = "BAG";
				DATATYPE_BAG datatype = new DATATYPE_BAG();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 39;
				string typeName = "EXAMPLES";
				DATATYPE_EXAMPLES datatype = new DATATYPE_EXAMPLES();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 40;
				string typeName = "AnonymousArray_40";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}